### PR TITLE
Add PULP_CERT and PULP_KEY paramater to access pulp api

### PR DESCRIPTION
**Pull request by raks-tt**

### CODE REVIEW

**Comment by raks-tt** [comment]
@ralphbean @jdcasey - Please review

**Comment by ralphbean** [comment]
@raks-tt this looks good to me. Have you been able to test it locally, functionally?

**Comment by raks-tt** [comment]
@ralphbean - Unfortunately no, I haven't been able to test this locally :/ Perhaps I should . I will keep you posted here. thanks for the suggestion

**Comment by raks-tt** [comment]
The pulp cert and service account was granted access but it didn't work when I tested. Keeping this open until I can successfully test this change

**Comment by raks-tt** [comment]
@ralphbean - I have verified and tested the changes locally:

```python
python pulp-prometheus-exporter.py
INFO:root:Serving prometheus data
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): rhsm-pulp.corp.redhat.com:443
DEBUG:urllib3.connectionpool:https://rhsm-pulp.corp.redhat.com:443 "POST /pulp/api/v2/tasks/search/ HTTP/1.1" 200 616493
DEBUG:urllib3.connectionpool:https://rhsm-pulp.corp.redhat.com:443 "POST /pulp/api/v2/tasks/search/ HTTP/1.1" 200 800
DEBUG:urllib3.connectionpool:https://rhsm-pulp.corp.redhat.com:443 "POST /pulp/api/v2/tasks/search/ HTTP/1.1" 200 3644
DEBUG:urllib3.connectionpool:https://rhsm-pulp.corp.redhat.com:443 "POST /pulp/api/v2/tasks/search/ HTTP/1.1" 200 616493
DEBUG:urllib3.connectionpool:https://rhsm-pulp.corp.redhat.com:443 "POST /pulp/api/v2/tasks/search/ HTTP/1.1" 200 800
DEBUG:urllib3.connectionpool:https://rhsm-pulp.corp.redhat.com:443 "POST /pulp/api/v2/tasks/search/ HTTP/1.1" 200 3644
DEBUG:urllib3.connectionpool:https://rhsm-pulp.corp.redhat.com:443 "POST /pulp/api/v2/tasks/search/ HTTP/1.1" 200 616493
DEBUG:urllib3.connectionpool:https://rhsm-pulp.corp.redhat.com:443 "POST /pulp/api/v2/tasks/search/ HTTP/1.1" 200 800


```

**Comment by ralphbean** [comment]
Merged. Thanks @raks-tt!

**Pull request merged**
